- name: Install MySQL
  apt:
    state: present
    pkg:
      - mysql-server-core-5.7
      - mysql-client-core-5.7
      - libmysqlclient-dev
      - python2.7
      - python-mysqldb
      - mysql-server
      - mysql-client

- name: Start the MySQL service
  action: service name=mysql state=started

- name: Copy .my.cnf file with root password credentials
  template: src=templates/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Remove the test database
  mysql_db: name=test state=absent

- name: Create deploy user for MySQL
  mysql_user: user="deply" host="%" password={{database.pass}} priv=*.*:ALL,GRANT

- name: Ensure anonymous users are not in the database
  mysql_user: user='' host=$item state=absent
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{item}} password={{database.pass}}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Create a new database
  mysql_db:
    name: '{{database.name}}'
    state: present

- name: Create a new database user for the application
  mysql_user:
    name: '{{database.user}}'
    password: '{{database.pass}}'
    priv: 'dodian_%.*:ALL'